## Reference https://github.com/krishnaik06/Complete-Python-Bootcamp/blob/main/10-Data%20Analysis%20With%20Python/10.1-numpy.ipynb

In [5]:
import numpy as np

#create a 1D array

arry1 = np.array([10, 20, 30, 40, 50])
print("1D Array:",arry1)
print(type(arry1))
print("Shape of 1D Array:", arry1.shape)

1D Array: [10 20 30 40 50]
<class 'numpy.ndarray'>
Shape of 1D Array: (5,)


In [6]:
np.__version__

'2.3.5'

In [7]:
# reshape
arry1_reshape = arry1.reshape(5,1)
print("Reshaped Array:\n", arry1_reshape)
print("Shape of Reshaped Array:", arry1_reshape.shape)

Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Shape of Reshaped Array: (5, 1)


In [8]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [9]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
## 2D array

array_2D =  np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2D)
print("Shape of 2D Array:", array_2D.shape)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of 2D Array: (3, 3)


In [12]:
array_2D.reshape(4,5)

ValueError: cannot reshape array of size 9 into shape (4,5)

In [13]:
array_2D.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
np.arange(0, 20, 2).reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [18]:
np.arange(0, 20, 2).reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
## Attributes
array_attri = np.array([[10,20,30],[40,50,60 ],[70,80,90]])

print("Array:\n", array_attri)
print("Shape:", array_attri.shape)
print("Dimensions: ", array_attri.ndim)  # 2 dimesions (rows, columsn)
print("Size:", array_attri.size)  # total number of elements
print("Data Type:", array_attri.dtype)
print("Item Size: ", array_attri.itemsize, "bytes")  # size of each element in bytes

Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
Dimensions:  2
Size: 9
Data Type: int64
Item Size:  8 bytes


In [30]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


In [36]:
print("Addition:", arr1 + arr2)
print("Subtraction:", arr2 - arr1)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)
print("Exponentiation:", arr1 ** 2)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Exponentiation: [ 1  4  9 16 25]


In [41]:
## Universal functions (ufuncs)
array_unifunc = np.array([11, 12, 13, 14, 15])

array_unifunc_sqrt = np.sqrt(array_unifunc)
print("Original Array:", array_unifunc)
print("Square Root of Array:", array_unifunc_sqrt)
print("Exponential of Array:", np.exp(array_unifunc))
print("Natural Logarithm of Array:", np.log(array_unifunc))
print("Sine of Array (in radians):", np.sin(array_unifunc))
print("Cosine of Array (in radians):", np.cos(array_unifunc))




Original Array: [11 12 13 14 15]
Square Root of Array: [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
Exponential of Array: [  59874.1417152   162754.791419    442413.39200892 1202604.28416478
 3269017.37247211]
Natural Logarithm of Array: [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]
Sine of Array (in radians): [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
Cosine of Array (in radians): [ 0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791]


In [46]:
## array slicing and indexing
array_slice = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original Array:", array_slice)
print("Element at index 3:", array_slice[3])  # 4th element
print("Elements from index 2 to 5:", array_slice[2:6])
print("Elementes in the reverse order:", array_slice[::-1])

Original Array: [ 10  20  30  40  50  60  70  80  90 100]
Element at index 3: 40
Elements from index 2 to 5: [30 40 50 60]
Elementes in the reverse order: [100  90  80  70  60  50  40  30  20  10]


In [52]:
##slcing 2D array
array_2d_slice = np.array([[10, 20, 30, 40],
                           [50, 60, 70, 80],
                           [90, 100, 110, 120],
                           [130, 140, 150, 160]])

print("Original 2D Array:\n", array_2d_slice)
print("Element at 2nd row and 3rd column:", array_2d_slice[1][2])
print("Element at 2nd row and 3rd column:", array_2d_slice[1, 2])
print("All Elements in the 3rd row and 2nd column:", array_2d_slice[2:, 1:])
print("Sub-array (rows 1-2, columns 2-3):\n", array_2d_slice[1:3, 2:4])
print("Sub-array (rows 1-2, columns 1-2):\n", array_2d_slice[1:3, 1:3])


Original 2D Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
Element at 2nd row and 3rd column: 70
Element at 2nd row and 3rd column: 70
All Elements in the 3rd row and 2nd column: [[100 110 120]
 [140 150 160]]
Sub-array (rows 1-2, columns 2-3):
 [[ 70  80]
 [110 120]]
Sub-array (rows 1-2, columns 1-2):
 [[ 60  70]
 [100 110]]


In [53]:
#Modify array elements
array_2d_slice[0, 0] = 999
print("Modified Array:\n", array_2d_slice)

Modified Array:
 [[999  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [54]:
array_2d_slice[:, 1] = 555
print("Modified Array with 2nd column changed:\n", array_2d_slice)

Modified Array with 2nd column changed:
 [[999 555  30  40]
 [ 50 555  70  80]
 [ 90 555 110 120]
 [130 555 150 160]]


In [60]:
## Statistical Operations
array_stats = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

calculate_mean = np.mean(array_stats)
print("Mean of all elements:", calculate_mean)
calculate_median = np.median(array_stats)
print("Median of all elements:", calculate_median)
calculate_mode = np.argmax(np.bincount(array_stats.flatten()))
print("Mode of all elements:", calculate_mode)
calculate_std = np.std(array_stats)
print("Standard Deviation of all elements:", calculate_std)


Mean of all elements: 50.0
Median of all elements: 50.0
Mode of all elements: 10
Standard Deviation of all elements: 25.81988897471611


In [62]:
##Logical operation
data = np.array([10, 25, 30, 45, 50, 65, 70, 85, 90])
data>50

array([False, False, False, False, False,  True,  True,  True,  True])

In [63]:
data[(data>30) &(data<=70)]

array([45, 50, 65, 70])