In [3]:
import numpy as np

In [4]:
##Asignment 1

arr1_1 = np.random.randint(1,21, size=(5,5))
arr1_1

array([[ 9, 19,  6, 16, 10],
       [12,  4, 12, 16, 19],
       [ 4,  7,  6, 20,  6],
       [ 7,  9, 14, 15, 12],
       [20, 16, 11, 18, 10]])

In [5]:
arr1_1[:, 2] = 1
arr1_1


array([[ 9, 19,  1, 16, 10],
       [12,  4,  1, 16, 19],
       [ 4,  7,  1, 20,  6],
       [ 7,  9,  1, 15, 12],
       [20, 16,  1, 18, 10]])

In [6]:
## Assignment 1

arr1_2 = np.arange(1, 17).reshape(4,4)
arr1_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
np.fill_diagonal(arr1_2, 0)
arr1_2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [8]:
## Assignment 2

arr2_1 = np.arange(1,37).reshape(6,6)
arr2_1


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
arr2_1[2:5, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [10]:
arr2_2 = np.random.randint(10, 51, size=(5,5))
arr2_2

array([[17, 23, 31, 45, 41],
       [40, 26, 43, 33, 38],
       [27, 47, 32, 30, 15],
       [13, 47, 39, 28, 13],
       [18, 27, 24, 47, 48]])

In [11]:
border_elems = np.concatenate([arr2_2[1:-1,0], arr2_2[0, :], arr2_2[-1, :], arr2_2[1:-1,-1]])
border_elems

array([40, 27, 13, 17, 23, 31, 45, 41, 18, 27, 24, 47, 48, 38, 15, 13])

In [12]:
## Assignment 3

arr3_1_1 = np.random.randint(10,50, size=(3,4))
arr3_1_2 = np.random.randint(51, 100, size = (3,4))
arr3_1_1, arr3_1_2

(array([[12, 38, 17, 19],
        [34, 39, 24, 35],
        [39, 24, 42, 10]]),
 array([[79, 58, 69, 77],
        [63, 87, 57, 89],
        [91, 87, 96, 52]]))

In [13]:
add = arr3_1_1 + arr3_1_2
add

array([[ 91,  96,  86,  96],
       [ 97, 126,  81, 124],
       [130, 111, 138,  62]])

In [14]:
subtract = arr3_1_2 - arr3_1_1
subtract

array([[67, 20, 52, 58],
       [29, 48, 33, 54],
       [52, 63, 54, 42]])

In [15]:
multiply = arr3_1_1 * arr3_1_2
multiply

array([[ 948, 2204, 1173, 1463],
       [2142, 3393, 1368, 3115],
       [3549, 2088, 4032,  520]])

In [16]:
division = arr3_1_2 / arr3_1_1  
division

array([[6.58333333, 1.52631579, 4.05882353, 4.05263158],
       [1.85294118, 2.23076923, 2.375     , 2.54285714],
       [2.33333333, 3.625     , 2.28571429, 5.2       ]])

In [17]:
arr3_2 = np.arange(1, 17).reshape(4,4)
arr3_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
sum_rows = arr3_2.sum(axis=1)
sum_rows

array([10, 26, 42, 58])

In [19]:
sum_columns = arr3_2.sum(axis=0)
sum_columns

array([28, 32, 36, 40])

In [20]:
## Assignment 4

arr4_1 = np.random.randint(1,100, size=(5,5))
arr4_1

array([[77, 59, 80, 72, 56],
       [86, 98, 25,  8, 50],
       [45, 52, 72, 41, 82],
       [89, 55, 95, 73, 53],
       [56, 95, 76, 69, 48]])

In [21]:
mean = np.mean(arr4_1)
print(mean)

64.48


In [22]:
print(np.median(arr4_1))

69.0


In [23]:
print(np.std(arr4_1))

21.7313046087896


In [24]:
print(np.var(arr4_1))

472.24960000000004


In [25]:
arr4_2 = np.arange(1, 10).reshape(3,3)
arr4_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
mean =  np.mean(arr4_2)
std_dev= np.std(arr4_2)

normalized_arr4_2 = (arr4_2 - mean) / std_dev
print(normalized_arr4_2)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [27]:
## Broadcasting
#Broadcasting is a powerful NumPy mechanism that allows arrays with different shapes to be 
# used together in arithmetic operations without explicitly replicating data.

arr5_1 = np.random.randint(1, 21, size=(3,3))
print(arr5_1)
row_arr = np.array([1,2,3])
result = arr5_1 + row_arr
print(result)

[[ 8 19  3]
 [ 3  8 15]
 [ 3  1  9]]
[[ 9 21  6]
 [ 4 10 18]
 [ 4  3 12]]


In [28]:
arr5_2 = np.random.randint(1, 21, size=(4,4))
print(arr5_2)
col_1Darry = np.array([1,2,3,4])
result2 = arr5_2 - col_1Darry.reshape(4,1)
result2

[[20  5 19  8]
 [20  7  6 16]
 [12  4  7  3]
 [11  1  9  3]]


array([[19,  4, 18,  7],
       [18,  5,  4, 14],
       [ 9,  1,  4,  0],
       [ 7, -3,  5, -1]])

In [29]:
## Assignment 6

arr6_1 = np.random.randint(1, 21, size=(3,3))
arr6_1

array([[ 8, 11, 17],
       [ 2, 13,  5],
       [ 8,  1,  4]])

In [30]:
#determinant
determinant = np.linalg.det(arr6_1)
print(determinant)

-1005.9999999999992



In [31]:
#inverse of the matrix
if determinant != 0:
    inversse_arr6_1 = np.linalg.inv(arr6_1)
    print(inversse_arr6_1)

[[-0.04671968  0.02683897  0.16500994]
 [-0.03180915  0.10337972  0.00596421]
 [ 0.10139165 -0.07952286 -0.08151093]]


In [32]:
eigenvalues, eigenvectors = np.linalg.eig(arr6_1)
print("Eigenvalues:", eigenvalues) 
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-5.35939167 21.71538974  8.64400193]
Eigenvectors:
 [[ 0.75156854 -0.82049685  0.39187909]
 [ 0.09587023 -0.41427146 -0.76557678]
 [-0.65265123 -0.39390871  0.51021856]]


In [33]:
## Assignment 7
import numpy as np
arr7_1 = np.arange(1, 10).reshape(3,3)  
arr7_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr7_1.reshape(1,9)  # Reshaping to 1D array with 9 elements

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
arr7_1.reshape(9,1)  # Reshaping to 1D array with 9 rows and 1 column

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
arr7_2 = np.random.randint(1, 21, size=(5,5))
arr7_2

array([[ 1,  1, 20,  7, 20],
       [17,  5, 19, 15, 13],
       [ 6,  6, 14, 11,  5],
       [16, 11, 13,  5, 14],
       [ 5,  6, 15,  9, 16]])

In [37]:
flatten_arry = arr7_2.flatten()
flatten_arry

array([ 1,  1, 20,  7, 20, 17,  5, 19, 15, 13,  6,  6, 14, 11,  5, 16, 11,
       13,  5, 14,  5,  6, 15,  9, 16])

In [38]:
flatten_arry.reshape(5,5)

array([[ 1,  1, 20,  7, 20],
       [17,  5, 19, 15, 13],
       [ 6,  6, 14, 11,  5],
       [16, 11, 13,  5, 14],
       [ 5,  6, 15,  9, 16]])

In [39]:
## Assignment 8
arr8_1 = np.random.randint(1,20, size=(5,5))
arr8_1

array([[12, 17, 13,  9, 16],
       [14, 19,  2, 16, 15],
       [ 6, 17, 12, 15, 19],
       [ 5,  3, 12, 13, 11],
       [14,  8,  7, 17, 14]])

In [40]:
# fancy indexing to select elements at the corners of the array
corners = arr8_1[[0, 0, 4, 4], [0, 4, 0, 4]]
corners

array([12, 16, 14, 14])

In [42]:
arr8_2 = np.random.randint(1,20, size=(4,4))
arr8_2

array([[17,  6,  6,  8],
       [ 1,  8,  5,  4],
       [ 9, 16,  4, 18],
       [ 3, 17, 16,  4]])

In [43]:
arr8_2[(arr8_2 > 10)] = 10
arr8_2

array([[10,  6,  6,  8],
       [ 1,  8,  5,  4],
       [ 9, 10,  4, 10],
       [ 3, 10, 10,  4]])

In [44]:
## Assignment 9
# Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float).
arr_9 = np.array([('Alice', 25, 55.5), ('Bob', 30, 75.0), ('Charlie', 22, 68.2)], 
                 dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
arr_9

array([('Alice', 25, 55.5), ('Bob', 30, 75. ), ('Charlie', 22, 68.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [45]:
sort_by_age= np.sort(arr_9, order='age')
sort_by_age

array([('Charlie', 22, 68.2), ('Alice', 25, 55.5), ('Bob', 30, 75. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [47]:
data_type = [('x', 'i4'), ('y', 'i4')]
points9_2 = np.array([(1,2), (3,4), (5,6), (2,5)], dtype=data_type)
points9_2

array([(1, 2), (3, 4), (5, 6), (2, 5)], dtype=[('x', '<i4'), ('y', '<i4')])

In [48]:
points_len = len(points9_2)
points_len

4

In [51]:
distances = np.zeros((points_len, points_len))
for row in range(points_len):
    for column in range(points_len):
        if row != column:

            dx = points9_2['x'][column] - points9_2['x'][row]
            print(f"dx: {dx}\n")
            dy = points9_2['y'][column] - points9_2['y'][row]
            print(f"dy: {dy}\n")
            distances[row, column] = np.sqrt(dx**2 + dy**2)
print(f"Euclidean Distance between points: {distances}")

dx: 2

dy: 2

dx: 4

dy: 4

dx: 1

dy: 3

dx: -2

dy: -2

dx: 2

dy: 2

dx: -1

dy: 1

dx: -4

dy: -4

dx: -2

dy: -2

dx: -3

dy: -1

dx: -1

dy: -3

dx: 1

dy: -1

dx: 3

dy: 1

Euclidean Distance between points: [[0.         2.82842712 5.65685425 3.16227766]
 [2.82842712 0.         2.82842712 1.41421356]
 [5.65685425 2.82842712 0.         3.16227766]
 [3.16227766 1.41421356 3.16227766 0.        ]]


In [ ]:
## Available solution for 9.2

# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [55]:
## Assignment 10
import numpy.ma  as ma
arr10_1 = np.random.randint(1, 101, size=(4,4))
arr10_1

array([[63, 53,  1, 13],
       [73, 35, 85, 54],
       [22,  4, 97, 97],
       [40, 68, 40, 52]])

In [56]:
masked_array = ma.masked_greater(arr10_1, 50)
masked_array

masked_array(
  data=[[--, --, 1, 13],
        [--, 35, --, --],
        [22, 4, --, --],
        [40, --, 40, --]],
  mask=[[ True,  True, False, False],
        [ True, False,  True,  True],
        [False, False,  True,  True],
        [False,  True, False,  True]],
  fill_value=999999)

In [60]:
sum_unmasked = masked_array.sum()
print(sum_unmasked)

155


In [61]:
arr10_2 = np.random.randint(1, 21, size=(3,3))
arr10_2

array([[ 6,  3, 20],
       [11, 14, 16],
       [19, 18, 11]])

In [62]:
##mask the diagonal elements
masked_diag = ma.masked_array(arr10_2, mask=np.eye(3, dtype=bool))
masked_diag

masked_array(
  data=[[--, 3, 20],
        [11, --, 16],
        [19, 18, --]],
  mask=[[ True, False, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=999999)

In [64]:
unmasked_mean=masked_diag.mean()
print(unmasked_mean)

14.5


In [66]:
#replace maked elements with mean of unmasked elements
new_masked_array = masked_diag.filled(unmasked_mean)
new_masked_array

array([[14,  3, 20],
       [11, 14, 16],
       [19, 18, 14]])